server:
  shutdown: graceful

spring:
  application:
    name: eureka-server
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: admin
      password: 1234
  profiles:
    active: peer1
