server:
  shutdown: graceful
  port: 8761

spring:
  application:
    name: eureka-server
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: admin
      password: 1234

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/